name: repository-dispatch

on:
  repository_dispatch:
    types: [example-dispatch-event]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: log-event
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Event payload: ${{ github.event.payload }}"
